name: Deploy to EC2

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install git if not installed
          which git || sudo yum install -y git
          
          # Install Python dependencies if needed
          which pip3 || sudo yum install -y python3-pip
          
          # Clean up previous deployment if it exists
          rm -rf ~/legal-ai-app
          
          # Clone the repository
          git clone https://github.com/avalon109/legal-ai-app.git ~/legal-ai-app
          cd ~/legal-ai-app
          
          # Set up or update virtual environment
          python3 -m venv ~/venv || echo "venv already exists"
          source ~/venv/bin/activate
          
          # Install requirements
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f backend/requirements.txt ]; then
            pip install -r backend/requirements.txt
          fi
          
          # Create or update systemd service file
          cat > ~/legal-ai-app.service << 'EOL'
          [Unit]
          Description=Legal AI Application
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/legal-ai-app
          Environment="PATH=/home/ec2-user/venv/bin"
          ExecStart=/home/ec2-user/venv/bin/python /home/ec2-user/legal-ai-app/app.py
          Restart=always
          RestartSec=3

          [Install]
          WantedBy=multi-user.target
          EOL
          
          # Move service file to systemd directory and set permissions
          sudo mv ~/legal-ai-app.service /etc/systemd/system/
          sudo chmod 644 /etc/systemd/system/legal-ai-app.service
          
          # Reload systemd, enable and restart service
          sudo systemctl daemon-reload
          sudo systemctl enable legal-ai-app.service
          sudo systemctl restart legal-ai-app.service
          
          # Check if service is running
          sudo systemctl status legal-ai-app.service
          
          # Show the last few lines of the logs
          sudo journalctl -u legal-ai-app.service -n 20
          
          # Make sure security group allows traffic on port 8000
          # (Note: This should be done manually in the AWS console)
          
          echo "Deployment completed"