name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 30m
        script: |
          # Install Python 3.12
          sudo yum update -y
          sudo yum install -y amazon-linux-extras
          sudo amazon-linux-extras enable python3.12
          sudo yum install -y python3.12 python3.12-pip python3.12-devel
          
          # Clean up and clone repository
          rm -rf ~/legal-ai-app
          git clone https://github.com/avalon109/legal-ai-app.git ~/legal-ai-app
          cd ~/legal-ai-app
          
          # Create fresh virtual environment
          rm -rf ~/venv
          python3.12 -m venv ~/venv
          source ~/venv/bin/activate
          
          # Install requirements
          python -m pip install --upgrade pip
          cd backend
          python -m pip install -r requirements.txt
          cd ..
          
          # Create systemd service
          cat > ~/legal-ai-app.service << 'EOL'
          [Unit]
          Description=Legal AI Application
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/legal-ai-app/backend
          Environment="PATH=/home/ec2-user/venv/bin"
          Environment="GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}"
          ExecStart=/home/ec2-user/venv/bin/python /home/ec2-user/legal-ai-app/backend/main.py
          Restart=always
          RestartSec=3
          StandardOutput=append:/var/log/legal-ai-app.log
          StandardError=append:/var/log/legal-ai-app.error.log

          [Install]
          WantedBy=multi-user.target
          EOL
          
          # Setup service
          sudo mv ~/legal-ai-app.service /etc/systemd/system/
          sudo chmod 644 /etc/systemd/system/legal-ai-app.service
          sudo touch /var/log/legal-ai-app.log /var/log/legal-ai-app.error.log
          sudo chown ec2-user:ec2-user /var/log/legal-ai-app.log /var/log/legal-ai-app.error.log
          
          # Start service
          sudo systemctl daemon-reload
          sudo systemctl enable legal-ai-app.service
          sudo systemctl restart legal-ai-app.service
          
          # Wait and check status
          sleep 5
          sudo systemctl status legal-ai-app.service
          
          # Show logs
          echo "=== Application Logs ==="
          sudo tail -n 20 /var/log/legal-ai-app.log
          echo "=== Error Logs ==="
          sudo tail -n 20 /var/log/legal-ai-app.error.log