name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        # UPDATED LINE: Changed from 30m to 60m.
        # You can adjust this further (e.g., 90m, 120m) if needed.
        timeout: 60m 
        script: |
          # Check if Rust is already installed
          if ! command -v rustc &> /dev/null; then
            echo "Installing Rust..."
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source "$HOME/.cargo/env"
            rustc --version
          else
            echo "Rust is already installed:"
            rustc --version
          fi
          
          # Install git and Python 3.12
          echo "TIMESTAMP: $(date) - Starting system package installation"
          sudo yum update -y
          sudo yum install -y git
          sudo yum install -y amazon-linux-extras
          sudo amazon-linux-extras enable python3.12
          sudo yum install -y python3.12 python3.12-pip python3.12-devel
          echo "TIMESTAMP: $(date) - Finished system package installation"
          
          # Clean up and clone repository
          echo "Cleaning up old deployment..."
          rm -rf ~/legal-ai-app
          
          echo "Cloning repository..."
          git clone https://github.com/avalon109/legal-ai-app.git ~/legal-ai-app
          
          echo "Verifying repository contents..."
          ls -la ~/legal-ai-app
          ls -la ~/legal-ai-app/backend
          
          cd ~/legal-ai-app
          
          # Create fresh virtual environment
          echo "Setting up virtual environment..."
          rm -rf ~/venv
          python3.12 -m venv ~/venv
          source ~/venv/bin/activate
          
          # Install requirements
          echo "TIMESTAMP: $(date) - Starting pip install"
          python -m pip install --upgrade pip setuptools wheel # Ensure pip and build tools are up to date
          cd backend
          ls -la  # Debug: show files in backend directory
          python -m pip install -v --prefer-binary --timeout 60 --default-timeout=60 -r requirements.txt
          echo "TIMESTAMP: $(date) - Finished pip install"
          cd ..
          
          # Create systemd service
          echo "Setting up systemd service..."
          cat > ~/legal-ai-app.service << 'EOL'
          [Unit]
          Description=Legal AI Application
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/legal-ai-app/backend
          Environment="PATH=/home/ec2-user/venv/bin:/home/ec2-user/.cargo/bin"
          Environment="GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}"
          ExecStart=/home/ec2-user/venv/bin/python /home/ec2-user/legal-ai-app/backend/main.py
          Restart=always
          RestartSec=3
          StandardOutput=append:/var/log/legal-ai-app.log
          StandardError=append:/var/log/legal-ai-app.error.log

          [Install]
          WantedBy=multi-user.target
          EOL
          
          # Setup service
          sudo mv ~/legal-ai-app.service /etc/systemd/system/
          sudo chmod 644 /etc/systemd/system/legal-ai-app.service
          sudo touch /var/log/legal-ai-app.log /var/log/legal-ai-app.error.log
          sudo chown ec2-user:ec2-user /var/log/legal-ai-app.log /var/log/legal-ai-app.error.log
          
          # Start service
          echo "Starting service..."
          sudo systemctl daemon-reload
          sudo systemctl enable legal-ai-app.service
          sudo systemctl restart legal-ai-app.service
          
          # Wait and check status
          sleep 5
          sudo systemctl status legal-ai-app.service
          
          # Show logs
          echo "=== Application Logs ==="
          sudo tail -n 20 /var/log/legal-ai-app.log
          echo "=== Error Logs ==="
          sudo tail -n 20 /var/log/legal-ai-app.error.log
